#!/bin/bash
# changeVolume

# Arbitrary but unique message tag
msgTag="9999"

# Get current volume. Need pamixer for this variable to work.
volume="$(pamixer --get-volume)"

# Send notification based on current volume
if [ "$volume" -gt "50" ]; then
    # Show the volume notification
    dunstify "VOLUME NOTIFICATION" -a "" -t 500 -r $msgTag -h int:value:$volume
elif [ "$volume" == "0" ]; then
    # Show the muted notification
    dunstify "VOLUME NOTIFICATION" -a "" -t 500 -r $msgTag -h int:value:$volume
else
    # Show low volume notification
    dunstify "VOLUME NOTIFICATION" -a "" -t 500 -r $msgTag -h int:value:$volume
fi

# Play the volume changed sound
canberra-gtk-play -f $HOME/.config/hypr/sounds/click.oga
