#!/bin/bash
# notifyPause

# Arbitrary but unique message tag
msgTag="9998"

# Get pause state
isPaused="$(dunstctl get-pause-level)"

# Send notification based on paused status
if [ "$isPaused" = "100" ]; then
    # Send paused notification, ignoring paused status
    dunstify "dunstPause" "paused" -a "" -t 1500 -r $msgTag
elif [ "$isPaused" == "0" ]; then
    # Show unpaused notification
    dunstify "dunstPause" "resumed" -a "" -t 1500 -r $msgTag
else
    # Show low volume notification
    dunstify "dunstPause" "" -t 1500 -r $msgTag -h int:value:$volume
fi
